# Circle CI 2.0 Especification
version: 2
jobs:
  build:
    # Docker image selected.
    docker:
      - image: 'kelsus/circleci-node-10.11:1.0'
    # Setup the ENV VARIABLES used in the  consequent steps. 
    environment:    
      # The Service Name must be the same you have in your package.json, Dockerfile &
      # docker-compose.yml.
      SERVICE_NAME: subtotal-multiple-aggregates
      # Git User Email & Name
      GIT_USER_EMAIL: ci@kelsus.com
      GIT_USER_NAME: CircleCI
    branches:
      only:
        - master
    steps:
      # Setup enviroment on Circle CI. This enable the support for docker-compose.
      # - setup_remote_docker
      # Enables a mode of the shell where all executed commands are printed to the terminal.
      - run: set -x
      # Checking out the project from the repository.
      - checkout
      - run:
          name: Allow access to private npm.
          command: printf "%s\n" "_auth=$ARTIFACTORY_TOKEN" "email=ci@kelsus.com" "always-auth=true" > .npmrc
      - run:
          name: For your npm command line client to work with Artifactory, you first need to set the default npm registry with an Artifactory npm repository
          command: npm config set registry https://kbsforce.jfrog.io/kbsforce/api/npm/npm/
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Configure git to commit and push the tag.
          command: git config --global user.email $GIT_USER_EMAIL && git config --global user.name $GIT_USER_NAME && git branch -u origin/$CIRCLE_BRANCH
      - deploy:
          name: Test, build and deploy npm package
          command: npm run deploy